timer:
	g++ timer_exam.cpp -lboost_timer -lboost_system -o timer_exam

date_time:
	g++ date_time_exam.cpp -lboost_date_time -o date_time_exam
	
time_duration:
	g++ time_duration_exam.cpp -lboost_date_time -o time_duration_exam

custom_surface_val:
	g++ custom_surface_val.cpp -lboost_date_time -o custom_surface_val_exam

turn_time_zone:
	g++ turn_time_zone.cpp -lboost_date_time -o turn_time_zone_exam

# 综合应用
month_calendar:
	g++ ./comprehensive_test/view_month_calendar.cpp -lboost_date_time -o ./comprehensive_test/view_month_calendar_exam

simple_date_cal:
	g++ ./comprehensive_test/simple_date_cal.cpp -lboost_date_time -o ./comprehensive_test/simple_date_cal_exam

free_credit_card:
	g++ ./comprehensive_test/free_credit_card.cpp -lboost_date_time -o ./comprehensive_test/free_credit_card_exam

microsec_clock:
	g++ ./comprehensive_test/microsec_clock.cpp -lboost_date_time -o ./comprehensive_test/microsec_clock_exam

calc_work_time:
	g++ ./comprehensive_test/calc_work_time.cpp -lboost_date_time -o ./comprehensive_test/calc_work_time_exam

clean:
	rm *.o *_exam ./comprehensive_test/*_exam|true