timer:
	g++ timer_exam.cpp -lboost_timer -lboost_system -o timer_exam

date_time:
	g++ date_time_exam.cpp -lboost_date_time -o date_time_exam

month_calendar:
	g++ ./comprehensive_test/view_month_calendar.cpp -lboost_date_time -o ./comprehensive_test/view_month_calendar_exam

simple_date_cal:
	g++ ./comprehensive_test/simple_date_cal.cpp -lboost_date_time -o ./comprehensive_test/simple_date_cal_exam

clean:
	rm *.o *_exam ./comprehensive_test/*_exam|true