cmake_minimum_required(VERSION 3.20)

if(NOT OFF)
    message("NOT OFF is true")
endif()
if(ON AND YES)
    message("ON AND YES is true")
endif()
if(TRUE AND NOTFOUND)
else()
    message("TRUE AND NOTFOUND is false")
endif()
if(A-NOTFOUND OR YES)
    message("A-NOTFOUND OR YES is true")
endif()