cmake_minimum_required(VERSION 3.20)
set(A FALSE)
set(B "A")
if(B)
    message("B is true")
endif()
if(${B})    # 接收到变量A，所以为false
else()
    message("\${B} is false")
endif()
while(NOT ${B})
    message("NOT \${B} is true")
    break()
endwhile()