cmake_minimum_required(VERSION 3.20)
set(a 10)
set(b "abc")
set(list 1;10;100)
if(11 GREATER a)
    message("11 greater a is true")
endif()
if(1 LESS 2)
    message("1 less 2 is true")
endif()
if(b STRLESS "b")
    message("b less \"b\" is true")
endif()
if(1.2.3 VERSION_LESS 1.10.1)
    message("1.2.3 less 1.10.1 is true")
endif()
if(abc MATCHES a..)
    message("abc matches a.. is true")
endif()
if(ab MATCHES a..)
else()
    message("ab matches a.. is false")
endif()
if(a IN_LIST list)
    message("a in_list list is true")
endif()