scoped_ptr:
	g++ sc_ptr.cpp -o sc_ptr_exam


# intrusive_ptr应用
intrusive_ptr1:	# 简单引用计数实现
	g++ in_ptr1.cpp -o in_ptr1_exam
	
intrusive_ptr2:
	g++ in_ptr2.cpp -o in_ptr2_exam

clean:
	rm *.o *_exam|true