noncopyable: noncopyable/non_c.cpp
	g++ noncopyable/non_c.cpp -o noncopyable/nonc_exam

ignored_unused:	ignored_unused/ig_unused.cpp
	g++ ignored_unused/ig_unused.cpp -o ignored_unused/igud_exam

clean:
	rm -f noncopyable/*.o noncopyable/*_exam
	rm -f ignored_unused/*.o ignored_unused/*_exam

.PHONY: clean