# shared_ptr相关应用
sh_ptr:
	g++ shared_ptr/sh_ptr_exam.cpp -o shared_ptr/sh_ptr_exam

pimpl:
	g++ shared_ptr/pimpl_implement.cpp -o shared_ptr/pimpl_exam

factory:
	g++ shared_ptr/fac_implement.cpp -o shared_ptr/fact_exam

# weak_ptr相关应用
w_ptr:
	g++ weak_ptr/w_ptr_exam.cpp -o weak_ptr/w_ptr_exam

clean:
	rm *.o *_exam|true
	rm shared_ptr/*.o shared_ptr/*_exam|true
	rm weak_ptr/*.o weak_ptr/*_exam|true