sh_ptr:
	g++ shared_ptr/sh_ptr_exam.cpp -o shared_ptr/sh_ptr_exam

pimpl:
	g++ shared_ptr/pimpl_implement.cpp -o shared_ptr/pimpl_exam

factory:
	g++ shared_ptr/fac_implement.cpp -o shared_ptr/fact_exam

clean:
	rm *.o *_exam|true
	rm shared_ptr/*.o shared_ptr/*_exam|true