# 暂时关闭抛弃内容，继续编译
auto_ptr:
	g++ auto_ptr_test.cpp -std=c++98 -Wno-deprecated-declarations -o auto_ptr_exam

unique_ptr:
	g++ u_ptr.cpp -o u_ptr_exam

shared_ptr:
	g++ sh_ptr.cpp -std=c++2a -o sh_ptr_exam

weak_ptr:
	g++ w_ptr.cpp -o w_ptr_exam

clean:
	rm *.o *_exam|true